package controller;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.ToggleGroup;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

public class calculadoraController {
	@FXML
	private Button btnCalcular;
	@FXML
	private ToggleGroup GrupoToggle;
	@FXML
	private TextField txtOperador1;
	@FXML
	private TextField txtOperador2;
	@FXML
	private TextField txtResultado;

	// Event Listener on Button[#btnCalcular].onAction
	@FXML
	public void calcular(ActionEvent event) {
		// TODO Autogenerated
	}
}
